index:
    path: /
    controller: App\Controller\PerseController::new


indexAdmin:
  path: /listEmployee
  controller: App\Controller\HomeController::index

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mgilet_notification:
  resource: "@MgiletNotificationBundle/Controller/"
  prefix: /notifications

updated_index:
  path:     /updated
  defaults: { _controller: App\Controller\HomeController::updatedIndex }


PDF:
  path: /admin/listPDF
  controller: App\Controller\HomeController::listPDF


ajoutEmployee:
  path:     /admin/ajoutEmployee
  defaults: { _controller:  App\Controller\EmployeeController::ajoutEmployee }

modifEmployee:
  path:     /admin//modifEmployee/{id}
  defaults: { _controller: App\Controller\EmployeeController::modifEmployee }

suppEmployee:
  path:     /admin/suppEmployee/{id}
  defaults: { _controller: App\Controller\EmployeeController::index }



ajoutConge:
  path:     /ajoutConge
  defaults: { _controller: App\Controller\CongeController::ajoutConge }

modifConge:
  path:     /modifConge/{id}
  defaults: { _controller: App\Controller\CongeController::modifConge }

suppConge:
  path:     /suppConge/{id}
  defaults: { _controller: App\Controller\CongeController::suppConge }

validerConge:
  path:     /admin/conge/{id}
  defaults: { _controller: App\Controller\CongeController::valider }

listConge:
  path:     /admin/listConge
  defaults: { _controller: App\Controller\CongeController::listConge }

soldeConge:
  path:     /admin/soldeConge
  defaults: { _controller: App\Controller\CongeController::soldeConge }

indexConge:
  path:     /admin/conge/list
  defaults: { _controller: App\Controller\CongeController::index }




search:
  path:     /search
  defaults: { _controller: App\Controller\EmployeeController::index }

presence:
  path:     /presence/{id}
  defaults: { _controller: App\Controller\HomeController::Present }




demandeAutorisation:
  path:     /autorisation/demande
  defaults: { _controller: App\Controller\AutorisationController::new }

demandeAutorisationAdmin:
  path:     /admin/autorisation/demande
  defaults: { _controller: App\Controller\AutorisationController::adminNew }


editAutorisation:
  path:     /autorisation/modifier/{id}
  defaults: { _controller: App\Controller\AutorisationController::update }

editAutorisationAdmin:
  path:     /admin/autorisation/modifier/{id}
  defaults: { _controller: App\Controller\AutorisationController::adminUpdate }

showAutorisation:
  path:     /autorisation/details
  defaults: { _controller: App\Controller\AutorisationController::index }

listAutorisation:
  path:     /autorisation/liste
  defaults: { _controller: App\Controller\AutorisationController::index}

suppAutorisation:
  path:     /autorisation/supp/{id}
  defaults: { _controller: App\Controller\AutorisationController::delete}

validerAutorisation:
  path:     /admin/autorisation/valider/{id}
  defaults: { _controller: App\Controller\AutorisationController::valider}




ajoutPerse:
  path:     /perse/ajouter
  defaults: { _controller: App\Controller\PerseController::new }


editPerse:
  path:     /perse/modifier/{id}
  defaults: { _controller: App\Controller\PerseController::edit }

showPerse:
  path:     /perse/details
  defaults: { _controller: App\Controller\PerseController::show }

listPerse:
  path:     /admin/perse/liste
  defaults: { _controller: App\Controller\PerseController::admin }

suppPerse:
  path:     /perse/supp/{id}
  defaults: { _controller: App\Controller\PerseController::delete }


PDFPerse:
  path: /admin/perse/rapport
  controller: App\Controller\PerseController::listPDF